enum AXAttributes {
    static let windows = "AXWindows"
    static let frontmost = "AXFrontmost"
    static let main = "AXMain"
    static let role = "AXRole"
    static let title = "AXTitle"
    static let position = "AXPosition"
    static let size = "AXSize"
    static let minSize = "AXMinSize"
    static let minimized = "AXMinimized"
    static let fullScreen = "AXFullScreen"
    static let fullScreenButton = "AXFullScreenButton"
    static let windowRole = "AXWindow"
    static let pressAction = "AXPress"
}
